### ISSUE TITLE
Crunchyroll queue page incomplete style

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Soitora/XHS-Styles#4]
https://www.crunchyroll.com/home/queue
Is broken/incomplete, there's white, unformatted borders around each show. Looks really bad.

**Comment by TBlazeWarriorT** [comment]
Found a solution for me
```
#source_home .landscape-grid li .queue-wrapper {
 background:#303030;
}

#source_home .queue-to-top {
 background: url(https://i.imgur.com/kBuiJBq.png) -3px 0 no-repeat;
}

#source_home .dropdown-collection {
    background: url(https://i.imgur.com/PofM8pS.png) 0 0 no-repeat;
}

#source_home .more-options {
    background: #111;
}

.collection-carousel-arrow {
    background: url(https://i.imgur.com/L9EFgy0.png) no-repeat -40px 42px;
}
```

**Comment by Soitora** [comment]
I don't have access to Crunchyroll anymore, I'll take your word for it and update.

**Comment by TBlazeWarriorT** [comment]
Just for reference, this is how it used to look like: 
![image](https://user-images.githubusercontent.com/25572454/56975522-64d45d80-6b47-11e9-82ca-a5a4c72bffce.png)
and this is how it looks like with my tweaks:

![image](https://user-images.githubusercontent.com/25572454/56975556-73227980-6b47-11e9-90c4-6154637cd668.png)

I personally also made some small tweaks to make text readable because some are really hard, but I'm not sure if they're worth sharing
![image](https://user-images.githubusercontent.com/25572454/56975629-9b11dd00-6b47-11e9-943c-d394754528c2.png)

**Comment by Soitora** [comment]
Ohh, looks good!
If you can send me before/after pictures of your other improvement then I'd be happy to implement it! :)

**Comment by TBlazeWarriorT** [comment]
I'll try, but I have to find the other changes I made xD

**Comment by TBlazeWarriorT** [comment]
To make text more readable, I changed everything using color #A8A8A8 to #F1F1F1 (slightly brighter white).

For the yellow balloon background, I used: (note that this only looks good with the brighter text above)
```
.availability-notes-high {
    background: #cc9;
}
```

To make the blue balloon backgrounds darker:
```
.availability-notes-low { /*Blue balloons BG*/
    background: #a6b6bf;
}
```

To make episode link in episode page look clickable by having a different color again, replaced
```
body, .new-template-body, textarea, ul.news-top-stories-row li a, .anime-lineup-blurb, span, ul.news-abbr .byline {
	color: #A8A8A8 !important;
}
```
with
```
body, .new-template-body, textarea, ul.news-top-stories-row li a, .anime-lineup-blurb, span, ul.news-abbr .byline { /*General text*/
	color: #F1F1F1 !important;
}

.new-template-body h1 { /*Ep name*/
    color: #AAA;
}
```

To make the episodes background in the episode list have a bit more contrast instead of being almost invisible, I changed (replaced) the color on this:
```
.portrait-element, #store_items li {
	background: #252525;
}
```

**Comment by TBlazeWarriorT** [comment]
![image](https://user-images.githubusercontent.com/25572454/56983084-2ba4e900-6b59-11e9-8cfe-bf2bc571faf2.png)
![image](https://user-images.githubusercontent.com/25572454/56983090-2e074300-6b59-11e9-9037-8eee3c175321.png)
Here's one comparison that shows most of the changes

**Comment by TBlazeWarriorT** [comment]
![image](https://user-images.githubusercontent.com/25572454/56983137-4bd4a800-6b59-11e9-889c-b9ee7d9e62a7.png)
![image](https://user-images.githubusercontent.com/25572454/56983182-6444c280-6b59-11e9-81c9-86f4088a8dbe.png)
Here's the episode title comparison

**Comment by TBlazeWarriorT** [comment]
Slightly more visible buttons:
```
.button.medium-button, a.button.medium-button, input.button.medium-button, span.button.medium-button {
    background: #292929;
}
```

Less white dropdown thingy (can't change the arrow?):
```
html.no-js body.main-page.responsive.enUS div#template_scroller.ad-skin div#template_container.cf.template-container.no-adskin div#template_body.cf.new-template-body div div#showmedia.cf.new_layout div#main_content.left div.guestbook.comments.box div#boxMEDIAKEY_781148.boxcontents div.guestbook-sort-bar div.sort-options.small-margin-right select#sort-selector {
    background: #333;
    color: #BBB;
    border: solid 1px #555;
}
```

![image](https://user-images.githubusercontent.com/25572454/56984325-239a7880-6b5c-11e9-9fa8-b009cebd1d1f.png)
![image](https://user-images.githubusercontent.com/25572454/56984358-33b25800-6b5c-11e9-8325-f240ebe427a3.png)

**Comment by Soitora** [comment]
Great work! :)
Pushing the code for this in a sec.

**Comment by TBlazeWarriorT** [comment]
A bit late but I found a last thing, I think it probably looks better in the modified bottom?
![image](https://user-images.githubusercontent.com/25572454/57055567-a3b30200-6c72-11e9-80ad-b2870bd9a285.png)
![image](https://user-images.githubusercontent.com/25572454/57055568-a7df1f80-6c72-11e9-87f3-346431aef73e.png)
```
#source_home #main_content .landscape-element {
    background: #303030;
}
```

**Comment by Soitora** [comment]
It looks better, I'll add it when I got time, thanks!

**Comment by TBlazeWarriorT** [comment]
another tiny thing, not too important also
current: 
![](https://i.imgur.com/tpDhYbz.png)
modified (note: I kept the white borders on hover on the undo button)
![](https://i.imgur.com/q242zaw.png)
```
.content-menu { /*Background for the "removed" thingy when you remove something from your queue*/
    background: #333;
    border: 0px solid #000; /*0px because IDK how to remove borders properly, so this just makes the border invis*/
}

html.no-js body.main-page.responsive.enUS div#template_scroller.ad-skin div#template_container.cf.template-container.no-adskin div#template_body.cf.new-template-body div#source_home div#container.cf div#main_content.left ul#sortable.landscape-grid.queue-sortable.ui-sortable li.queue-item div.content-menu.cf.undo-queue-remove.small-margin-bottom button.button.default-button.button-padding.small-button.right {
    /*This should make the undo button less invisible-y, else it has the same color as the background*/
    background:#444;
}
```
Uhh, I think the button fix might only work in the english crunchyroll or something because I just did "copy css path" in F12 mode, idk the proper way because that buttons just grabs defaut button css otherwise and I'm bad at css

**Comment by Soitora** [comment]
Often when you copy css path you can edit out a big part of the path and it'll still work but be more flexible.

Also, removing borders usually is just `border: 0px !important;` or `border: none !important;`
The !important tag is useful everywhere when overwriting code using Stylus or similar.

I'm gonna soon start on a rework of the theme I think, I'll see wether to implement this before or not. Thank you
